import { Link } from 'react-router-dom';
import { Header } from '@/components/Header';
import { Shield, BookOpen, Zap, FileQuestion, Code, ArrowLeft } from 'lucide-react';

const sections = [
  {
    id: 'getting-started',
    title: 'Getting Started',
    icon: Zap,
    content: [
      {
        subtitle: 'What is DeepTrust?',
        description: 'DeepTrust is an AI-powered platform designed to detect deepfakes and manipulated media content. Using advanced neural networks and explainable AI techniques, we provide transparent and reliable media verification.',
      },
      {
        subtitle: 'How It Works',
        description: 'Our system analyzes images and videos using state-of-the-art deep learning models. When content is analyzed, we provide not just a detection result, but also visual explanations showing which regions influenced the decision using Grad-CAM visualizations.',
      },
    ],
  },
  {
    id: 'using-detection',
    title: 'Using the Detection Tool',
    icon: Shield,
    content: [
      {
        subtitle: 'Upload Your Media',
        description: 'Navigate to the Detection page and upload an image or video file. Supported formats include JPEG, PNG for images and MP4, AVI for videos. Maximum file size is 100MB.',
      },
      {
        subtitle: 'Understanding Results',
        description: 'After analysis, you\'ll receive a confidence score indicating the likelihood that the content is AI-generated or manipulated. Scores above 70% suggest potential manipulation, while scores below 30% indicate likely authentic content.',
      },
      {
        subtitle: 'Explainability View',
        description: 'Click on "View Explanation" to see Grad-CAM heatmaps highlighting suspicious regions. Warmer colors (red/yellow) indicate areas that most influenced the AI\'s decision.',
      },
    ],
  },
  {
    id: 'faq',
    title: 'Frequently Asked Questions',
    icon: FileQuestion,
    content: [
      {
        subtitle: 'Is my data stored?',
        description: 'No. All analysis happens in real-time and your uploaded media is immediately discarded after processing. We are privacy-first and never store user content.',
      },
      {
        subtitle: 'What types of deepfakes can be detected?',
        description: 'Our models are trained to detect face swaps, synthetic faces generated by GANs, face reenactment, and other common deepfake techniques. The system is continuously updated to detect new manipulation methods.',
      },
      {
        subtitle: 'How accurate is the detection?',
        description: 'Our models achieve over 95% accuracy on benchmark datasets. However, detection accuracy can vary based on content quality, manipulation sophistication, and compression artifacts.',
      },
      {
        subtitle: 'Can I use DeepTrust commercially?',
        description: 'Yes. DeepTrust can be integrated into commercial workflows. Contact us for API access and enterprise licensing options.',
      },
    ],
  },
  {
    id: 'api',
    title: 'API Integration',
    icon: Code,
    content: [
      {
        subtitle: 'REST API',
        description: 'DeepTrust offers a REST API for programmatic access. Authenticate using API keys and send POST requests with media files to receive JSON responses with detection results and confidence scores.',
      },
      {
        subtitle: 'Response Format',
        description: 'API responses include: detection confidence (0-100), classification label (authentic/manipulated), processing time, and optional explainability data with heatmap coordinates.',
      },
      {
        subtitle: 'Rate Limits',
        description: 'Free tier: 100 requests/day. Pro tier: 10,000 requests/day. Enterprise: Unlimited. Contact us for custom rate limits and SLA guarantees.',
      },
    ],
  },
];

const Documentation = () => {
  return (
    <div className="min-h-screen bg-background">
      <Header />
      
      <div className="pt-24 pb-20 px-4">
        <div className="container mx-auto max-w-5xl">
          {/* Header */}
          <div className="mb-12">
            <Link 
              to="/" 
              className="inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors mb-6"
            >
              <ArrowLeft className="w-4 h-4" />
              Back to Home
            </Link>
            
            <div className="flex items-center gap-3 mb-4">
              <div className="p-3 rounded-xl bg-primary/10">
                <BookOpen className="w-8 h-8 text-primary" />
              </div>
              <h1 className="text-4xl md:text-5xl font-bold text-foreground">
                Documentation
              </h1>
            </div>
            <p className="text-lg text-muted-foreground">
              Everything you need to know about using DeepTrust for media verification
            </p>
          </div>

          {/* Table of Contents */}
          <div className="glass-card rounded-2xl p-6 mb-12">
            <h2 className="text-xl font-semibold text-foreground mb-4">Table of Contents</h2>
            <nav className="grid sm:grid-cols-2 gap-3">
              {sections.map((section) => (
                <a
                  key={section.id}
                  href={`#${section.id}`}
                  className="flex items-center gap-3 p-3 rounded-lg hover:bg-accent transition-colors group"
                >
                  <section.icon className="w-5 h-5 text-primary" />
                  <span className="text-foreground font-medium group-hover:text-primary transition-colors">
                    {section.title}
                  </span>
                </a>
              ))}
            </nav>
          </div>

          {/* Documentation Sections */}
          <div className="space-y-12">
            {sections.map((section) => (
              <section key={section.id} id={section.id} className="scroll-mt-24">
                <div className="glass-card rounded-2xl p-8">
                  <div className="flex items-center gap-3 mb-6">
                    <div className="p-2 rounded-lg bg-accent">
                      <section.icon className="w-6 h-6 text-primary" />
                    </div>
                    <h2 className="text-2xl md:text-3xl font-bold text-foreground">
                      {section.title}
                    </h2>
                  </div>
                  
                  <div className="space-y-6">
                    {section.content.map((item, index) => (
                      <div key={index} className="border-l-2 border-primary/30 pl-6">
                        <h3 className="text-lg font-semibold text-foreground mb-2">
                          {item.subtitle}
                        </h3>
                        <p className="text-muted-foreground leading-relaxed">
                          {item.description}
                        </p>
                      </div>
                    ))}
                  </div>
                </div>
              </section>
            ))}
          </div>

          {/* CTA Section */}
          <div className="mt-16 glass-card rounded-2xl p-10 text-center">
            <h2 className="text-2xl md:text-3xl font-bold text-foreground mb-4">
              Ready to try DeepTrust?
            </h2>
            <p className="text-muted-foreground mb-6 max-w-xl mx-auto">
              Start detecting deepfakes and manipulated media with our advanced AI-powered tools.
            </p>
            <Link 
              to="/detect" 
              className="btn-hero inline-flex items-center gap-2"
            >
              Go to Detection
              <Shield className="w-5 h-5" />
            </Link>
          </div>

          {/* Footer Note */}
          <div className="mt-12 text-center">
            <p className="text-sm text-muted-foreground">
              Need more help? Contact us at{' '}
              <a href="mailto:support@deeptrust.ai" className="text-primary hover:underline">
                support@deeptrust.ai
              </a>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Documentation;
